// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require("Verifier");

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
const {
  proof: { a, b, c },
  inputs
} = require("./proof.json");

// Test verification with incorrect proof

contract("Test Square Verifier", async accounts => {
  var verifier;
  before("setup contract", async () => {
    verifier = await Verifier.new();
  });

  it(`verify with correct proof`, async () => {
    const v = await verifier.verifyTx.call(a, b, c, inputs);
    //console.log(v);
    //assert.equal(v, false, "Failed verify true.");
  });

  it(`verify with correct proof`, async () => {
    const cmod = [c[0], c[1].slice(0, -5) + "00000"];
    const v = await verifier.verifyTx(a, b, cmod, inputs);
    //console.log(v);
    //assert.equal(v, true, "Failed verify false.");
  });
});
