inter:
	docker run -v /Users/carltonjoseph/cj/cj2019/courses/udacity-blockchain-part2/capstone/house-listing/zokrates/code:/home/zokrates/code -ti zokrates/zokrates /bin/bash

inter3:
	docker run -v /Users/carltonjoseph/cj/cj2019/courses/udacity-blockchain-part2/capstone/house-listing/zokrates/code:/home/zokrates/code -ti zokrates/zokrates:0.3.0 /bin/bash

dist:
	cp -rf ./code/square/verifier.sol ../eth-contracts/contracts/Verifier.sol
	cp -rf ./code/square/proof.json ../eth-contracts/test/
